config/routes.rb
ShottenTotten::Application.routes.draw do
  root to: "pages#home"

  resources :games, only: [:create, :show] do
    get 'user_info', :on => :collection

    resources :users, only: :create

    resources :cards, only: [:index, :update]

    resources :stones, only: [:index, :show, :update]
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :game
  belongs_to :user

  attr_accessible :color, :position_on_board, :position_on_hand, :value

  scope :on_board, where("position_on_board IS NOT NULL")
  scope :on_hand, where("position_on_hand IS NOT NULL")
  scope :on_deck, where("user_id IS NULL")

  scope :by_user, ->(user_id) { where(user_id: user_id) }

end

app/models/game.rb
class Game < ActiveRecord::Base

  COLORS = %w{black red blue orange purple green}
  NUMBERS = (1..9).to_a
  MAX_CARDS_ON_HAND = 6

  has_many :users
  has_many :cards
  has_many :stones

  attr_accessible :position, :turn_id

  after_create :setup

  def setup
    cards_data = []
    COLORS.each do |color|
      NUMBERS.each do |number|
        cards_data << {color: color, value: number}
      end
    end
    cards_data.shuffle!
    self.cards.create(cards_data)

    9.times do |position|
      self.stones.create(position: position)
    end
  end

  def start
    self.users.each {|user| deal_to(user) }
    assign_turn_to_players
  end

  def deal_to(user)
    available_positions = available_positions_on_hand(user)
    selected_cards = self.cards.on_deck.limit(available_positions.count)
    selected_cards.each do |card|
      card.user = user
      card.position_on_hand = available_positions.shift
      card.save
    end
  end

  def available_positions_on_hand(user)
    used_positions = self.cards.on_hand.by_user(user).select(:position_on_hand).map(&:position_on_hand)
    (1..MAX_CARDS_ON_HAND).to_a - used_positions
  end

  def assign_turn_to_players
    user_ids = self.users.map &:id
    next_turn = if turn_id.present?
                  (user_ids - [turn_id])[0]
                else
                  user_ids.sample
                end
    update_attribute(:turn_id, next_turn)
  end

end

app/models/stone.rb
class Stone < ActiveRecord::Base
  belongs_to :game
  belongs_to :user

  attr_accessible :position, :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :token, :username

  belongs_to :game
  has_many :stones

  before_create :set_token, :set_position

  protected

  def set_token
    self.token = Digest::MD5.base64digest("#{self.id}#{self.username}").gsub(/[\/&+]/,'')
  end

  def set_position
    self.position = self.game.users.count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :load_user, :load_game

  respond_to :json

  def index
    @cards = @game.cards.on_board
    @cards += @game.cards.on_hand.by_user(@user) if @user
    respond_with @cards
  end

  def update
    @card = @game.cards.by_user(@user).find(params[:id])
    @card.update_attributes(
      position_on_hand: params[:position_on_hand],
      position_on_board: params[:position_on_board]
    )
    @game.deal_to(@user)
    @game.assign_turn_to_players
    render json: @card
  end

  protected

  def load_user
    if params[:token]
      @user = User.find_by_token(params[:token])
    end
  end

  def load_game
    @game = Game.find(params[:game_id])
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  respond_to :html, :json

  def create
    @game = Game.new
    if @game.save
      redirect_to @game
    else
      redirect_to root_path, flash: {error: "Your game couldn't be created."}
    end
  end

  def show
    @game = Game.find(params[:id])
    respond_with @game
  end

  def user_info
    respond_with({
      id: "#{Game.last.id}#{((Random.rand * 899).to_i+100)}#{((Random.rand * 899).to_i+100)}",
      socketURL: self.get_socket_url
    })
  end

  protected
  def get_socket_url
    Rails.env.production? ? "" : "http://0.0.0.0:5000"
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/controllers/stones_controller.rb
class StonesController < ApplicationController
  before_filter :load_game

  respond_to :json

  def index
    @stones = @game.stones
    respond_with @stones
  end

  def show
    @stone = @game.stones.find(params[:id])
    render json: @stone
  end

  def update
    @stone = @game.stones.find(params[:id])
    @stone.update_attribute(:user_id, params[:user_id])
    render json: @stone
  end

  protected

  def load_game
    @game = Game.find(params[:game_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  after_filter :check_for_game_setup

  respond_to :json

  def create
    @game = Game.find(params[:game_id])
    @user = @game.users.new
    @user.id, @user.username = params[:id], params[:username]
    @user.save
    render json: @user
  end

  protected

  def check_for_game_setup
    @game.start if @game.users.count == 2
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper

  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

end

app/views/games/show.html.haml
#game
  %canvas#canvasBg{width: 900, height: 600}
  #overlapping
    %canvas#canvasEntities{width: 900, height: 600}

#users
  %span.block Waiting Oponent...

= javascript_tag do
  window.game_id = #{@game.id};

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      = content_for?(:title) ? yield(:title) : "Schotten Totten"
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag "application", media: "all"
    = csrf_meta_tag
    = yield :head

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          = link_to "Schotten Totten", root_path, class: "brand"
          .nav-collapse
            %ul.nav
              %li.active= link_to "Home", root_path

    .container-fluid
      .row-fluid
        - flash.each do |name, msg|
          = content_tag :div, msg, id: "flash_#{name}"

        = yield

    = javascript_include_tag "application", debug: Rails.env.development? && params[:jsdebug]

app/views/layouts/games.html.haml
!!!
%html

  %head
    %title
      = content_for?(:title) ? yield(:title) : "Schotten Totten"
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag "game", media: "all"
    = csrf_meta_tag
    = yield :head

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          = link_to "Schotten Totten", root_path, class: "brand"
          .nav-collapse
            %ul.nav
              %li.active= link_to "Home", root_path

    .container-fluid
      .row-fluid
        - flash.each do |name, msg|
          = content_tag :div, msg, id: "flash_#{name}"

        = yield

    = javascript_include_tag "game", debug: Rails.env.development? && params[:jsdebug]

app/views/pages/home.html.haml
- title "Homepage"

= link_to 'Create a new Game', games_path, method: :post